### ISSUE TITLE
Use of = instead of == means patch method always uses hwnd

### ISSUE THREAD

**Issue by bonesbro** [Sumwunn/KeyboardShortcutsFix#2]
https://github.com/Sumwunn/KeyboardShortcutsFix/blob/b41118984a64ba84a2d3ef52cfed29efd814f441/KeyboardShortcutsFix/KeyboardShortcutsFix.cpp#L138

Typo means that these two checks don't work correctly.

**Comment by Sumwunn** [comment]
Fixed.

Thanks!
