### ISSUE TITLE
Keyboard handler keeps redirecting input even when Skyrim is minimized

### ISSUE THREAD

**Issue by bonesbro** [Sumwunn/KeyboardShortcutsFix#3]
Repro steps:

1. Install KeyboardShortcutsFix
2. Start Skyrim SE, load a game, and open the console
3. Alt tab, open notepad or a web browser, and type something
4. Alt tab back into SkyrimSE and look at the console

Expected: The console has no text in it
Actual: The keystrokes you typed into other apps while Skyrim was minimized also appear

**Comment by Sumwunn** [comment]
Fixed.

Thanks!
